// db-types.test.ts — Unit tests for `db-types.ts` (P3.7 Slice 1).
//
// What we test (no DB + no CLI required)
// --------------------------------------
// - `readGeneratedTypes` correctly reads a generated file when present,
//   returns null when absent. This is the only pure helper we test
//   here — the actual CLI invocation is integration-tested against a
//   running local Supabase (see db-types-README.md).
// - `redactDatabaseUrl` (re-exported via db-bootstrap) is reused, not
//   re-tested here — see db-bootstrap.test.ts.
//
// What we intentionally do NOT test
// ----------------------------------
// - The actual `supabase gen types` invocation. Requires a running
//   local Supabase + the CLI. Mocking `spawnSync` here would only
//   verify that we call it the right number of times — it would NOT
//   verify that the generated content matches the CLI's actual output
//   shape. The right place for that test is CI's
//   `pnpm db:bootstrap && pnpm db:types` job.
//
// Run: `pnpm test db-types`.

import { writeFileSync, rmSync, mkdirSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it, afterAll } from 'vitest'

import { readGeneratedTypes } from './db-types'

describe('readGeneratedTypes', () => {
  const tmpDirs: string[] = []

  afterAll(() => {
    for (const d of tmpDirs) rmSync(d, { recursive: true, force: true })
  })

  function makeTmp(label: string): string {
    const d = join(tmpdir(), `db-types-${label}-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(d, { recursive: true })
    tmpDirs.push(d)
    return d
  }

  it('returns null when the generated file does not exist', () => {
    const dir = makeTmp('missing')
    const target = join(dir, 'types.generated.ts')
    expect(existsSync(target)).toBe(false)
    expect(readGeneratedTypes(target)).toBeNull()
  })

  it('returns the file content when present', () => {
    const dir = makeTmp('present')
    const target = join(dir, 'types.generated.ts')
    const sample = 'export type Database = { public: { Tables: {} } }\n'
    writeFileSync(target, sample, 'utf8')
    expect(readGeneratedTypes(target)).toBe(sample)
  })

  it('round-trips a multi-line generated file without mutation', () => {
    const dir = makeTmp('multiline')
    const target = join(dir, 'types.generated.ts')
    const sample = [
      '// AUTO-GENERATED by pnpm db:types',
      'export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]',
      '',
      'export type Database = {',
      '  public: {',
      '    Tables: { products: { Row: { id: number; title: string } } },',
      '  },',
      '}',
      '',
    ].join('\n')
    writeFileSync(target, sample, 'utf8')
    expect(readGeneratedTypes(target)).toBe(sample)
  })

  it('returns null for an empty path (smoke check on default fallback)', () => {
    // Calling with no args uses the default repo-root path. We don't
    // assert anything about its content (it may or may not exist on a
    // given machine), only that the call returns string | null without
    // throwing. This guards against accidental exceptions in the helper.
    const result = readGeneratedTypes()
    expect(result === null || typeof result === 'string').toBe(true)
  })
})
